services:
  blog:
    image: dkr.cidrs.net/noblog:latest
    build: .
    restart: unless-stopped
    ports:
      - "3001:5001"
    environment:
      - BLOG_TITLE=NoBlog
      - SPELL_CHECK=true
      - APP_VERSION=${APP_VERSION:-dev}
      - NOBLOG_WRITE_TOKEN=${NOBLOG_WRITE_TOKEN:-}
    volumes:
      - blog_uploads:/app/uploads
      - blog_db:/app/instance

volumes:
  blog_uploads:
  blog_db:
